version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: game_server-app
    depends_on:
      - db
    networks:
      - server_network

  db:
    image: "python:3.11-slim"
    volumes:
      - ./database:/database

networks:
  server_network:
    external: true